apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-lens-service
  namespace: ichiban
spec:
  replicas: 2
  selector:
    matchLabels:
      app: portfolio-lens-service
      component: ichiban
  template:
    metadata:
      labels:
        app: portfolio-lens-service
        component: ichiban
    spec:
      imagePullSecrets:
        - name: harbor-credentials
      containers:
        - name: service
          image: harbor.zainokta.com/ichiban/portfolio-lens:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          resources:
            limits:
              cpu: "128m"
              memory: "128Mi"
            requests:
              cpu: "128m"
              memory: "128Mi"