apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-lens-service
  namespace: ichiban
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfolio-lens-service
      component: ichiban
  template:
    metadata:
      labels:
        app: portfolio-lens-service
        component: ichiban
    spec:
      imagePullSecrets:
        - name: harbor-credentials
      containers:
        - name: service
          image: harbor.zainokta.com/ichiban/portfolio-lens:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          env:
            - name: ENVIRONMENT
              value: "production"
            - name: PROJECT_NAME
              value: "PortfolioLens"
            - name: PROJECT_DESCRIPTION
              value: "Suggesting the ability to look deeply into my work experience"
            - name: VERSION
              value: "1.0.0"
            - name: PORT
              value: "8000"
            - name: DB_HOST
              value: "postgres-service"  # Update this to your PostgreSQL service name
            - name: DB_PORT
              value: "16348"
            - name: DB_NAME
              value: "portfolio"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: portfolio-secrets
                  key: db-user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: portfolio-secrets
                  key: db-password
            - name: ALLOWED_ORIGINS
              value: "https://zainokta.com"
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: portfolio-secrets
                  key: openai-api-key
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            limits:
              cpu: "128m"
              memory: "384Mi"
            requests:
              cpu: "128m"
              memory: "384Mi"